# Generated by Django 5.1.1 on 2024-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
