# Generated by Django 5.1.1 on 2024-09-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
    ]
