# Generated by Django 5.1.1 on 2024-09-25 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(null=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
